name: Rebuild Workload images (triggerable)

on:
  workflow_dispatch:
    inputs:
      workload_commit:
        description: "The workload SHA commit to build"
        required: true
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  workload-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: workload
          push: true
          tags: |
            ghcr.io/heliaxdev/ant-workload:${{ github.event.inputs.workload_commit }}
            us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository/workload:${{ github.event.inputs.workload_commit }}
          cache-from: type=gha
          cache-to: type=gha,mode=max