name: Rebuild Check image (triggerable)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'check/**'
  push:
    branches:
      - master
    paths:
      - 'check/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: check
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/heliaxdev/ant-check:latest
            us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository/check:latest
          cache-from: type=gha,scope=check-image
          cache-to: type=gha,scope=check-image,mode=max