name: Rebuild Workload images (triggerable)

on:
  workflow_dispatch:
    inputs:
      workload_commit:
        description: "The workload SHA commit to build"
        required: true
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  workload-container:
    runs-on: ubuntu-latest
    env:
      antithesis_registry_url: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.antithesis_registry_url }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Workload Container
        run: |
          registry_url="${{ env.antithesis_registry_url }}" sha="${{ github.event.inputs.workload_commit }}" make build-workload
          docker push ${{ env.antithesis_registry_url }}/workload:${{ github.event.inputs.workload_commit }}

          docker tag ${{ env.antithesis_registry_url }}/workload:${{ github.event.inputs.workload_commit }} ghcr.io/heliaxdev/ant-workload:${{ github.event.inputs.workload_commit }}
          docker push ghcr.io/heliaxdev/ant-workload:${{ github.event.inputs.workload_commit }}