jobs:
  copy-images:
    strategy:
      fail-fast: false
      matrix:
        images:
          - org: "cosmos"
            image: "gaia"
            tag: "v22.3.1"
          - org: "heliaxdev"
            image: "hermes"
            tag: "1.13.0"

    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image from GHCR
        run: |
          docker pull ghcr.io/${{ matrix.images.org }}/${{ matrix.images.image }}:${{ matrix.images.tag }}
      - name: Retag for destination registry
        run: |
          docker tag ghcr.io/${{ matrix.images.org }}/${{ matrix.images.image }}:${{ matrix.images.tag }} us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository/${{ matrix.images.image }}:${{ matrix.images.tag }}
      - name: Push to destination
        run: |
          docker push us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository/${{ matrix.images.image }}:${{ matrix.images.tag }}
