name: Run antithesis daily (cron)

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  daily:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
      matrix:
        runs:
          - image: "main-inst"
            genesis: "main"
            masp_indexer: "0eee762147fe8d440d82c71089a3c0e7ea02c785"
            workload: "with-namada-3f34d31"
            duration: 4
            config: "main"
          - image: "v1.1.2-inst"
            genesis: "v1.1.2"
            config: "v1.1.2"
            masp_indexer: "master"
            workload: "master"
            duration: 4

    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.7
        with:
          config_image: namada-config:${{ matrix.runs.config }}
          notebook_name: namada2
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-genesis:${{ matrix.runs.genesis }},namada:${{ matrix.runs.image }},workload:master,check:latest,masp-indexer-block-filter:${{ matrix.runs.masp_indexer }},masp-indexer-webserver:${{ matrix.runs.masp_indexer }},masp-indexer-chain:${{ matrix.runs.masp_indexer }}
          email_recipients: |
            gianmarco@heliax.dev,yuji@heliax.dev,heliax-antithesis-aaaammxjv6zgaqxcdury4ktshq@antithesisgroup.slack.com
          additional_parameters: |
            custom.duration=${{ matrix.runs.duration }}
            custom.faults=true
