name: Run antithesis daily (cron)

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  daily:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
      matrix:
        runs:
          - image: "main"
            masp_indexer: "master"
            faults: true
          - image: "main-inst"
            masp_indexer: "master"
            faults: true
            
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.5
        with:
          config_image: namada-config:main
          notebook_name: namada2
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-genesis:main,namada:${{ matrix.runs.image }},workload:latest,check:latest,masp-block-filter:${{ matrix.runs.masp_indexer }},masp-indexer-webserver:${{ matrix.runs.masp_indexer }},masp-indexer-chain:${{ matrix.runs.masp_indexer }}
          email_recipients: |
            gianmarco@heliax.dev,heliax-antithesis-aaaammxjv6zgaqxcdury4ktshq@antithesisgroup.slack.com
          additional_parameters: |
            custom.duration=3
            custom.faults=${{ matrix.runs.faults }}
