name: Run antithesis daily (cron)

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  daily:
    runs-on: [ubuntu-latest]
    timeout-minutes: 1440
    strategy:
      matrix:
        runs:
          - namada: "main"
            genesis: "main"
            masp_indexer: "master"
            workload: "master"
            check: "master"
            duration: 14400
            config: "main"
          - image: "v101.0.0"
            genesis: "v101.0.0"
            config: "v101.0.0"
            masp_indexer: "v1.3.0"
            workload: "for-stable-namada"
            check: "master"
            duration: 14400
    env:
      NAMADA_GENESIS_IMAGE: "ghcr.io/heliaxdev/ant-namada-genesis:${{ matrix.runs.inputs.genesis }}"
      NAMADA_IMAGE: "ghcr.io/heliaxdev/ant-namada:${{ matrix.runs.namada }}"
      MASP_INDEXER_IMAGE_PREFIX: "ghcr.io/heliaxdev/ant-masp-indexer"
      MASP_INDEXER_IMAGE_TAG: ${{ matrix.runs.masp_indexer }}
      WORKLOAD_IMAGE: "ghcr.io/heliaxdev/ant-workload:${{ matrix.runs.workload }}"
      CHECK_IMAGE: "ghcr.io/heliaxdev/ant-check:${{ matrix.runs.check }}"
      TEST_TIME_SEC: ${{ matrix.runs.duration }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-compose-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-compose-
      - name: Docker compose build
        run:  docker compose -f config/docker-compose.yml build
      - name: Generate random number for the test seed
        run: echo "TEST_SEED=$RANDOM" >> $GITHUB_ENV
      - name: Run test
        run: ./run.sh
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-*.log
