name: Rebuild Namada images

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "The namada SHA commit to build"
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        images:
          - make: "build-config"
            image: "config"
          - make: "build-genesis"
            image: "genesis"
          - make: "build-namada"
            image: "namada"
          - make: "build-namada-inst"
            image: "namada-inst"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ANTITHESIS_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Build image ${{ matrix.images.name }}
        run: sha=${{ github.event.inputs.commit }} make ${{ matrix.images.make }}