name: Rebuild Namada images

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "The namada SHA commit to build"
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        regsitry_url: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
    strategy:
      fail-fast: true
      matrix:
        images:
          - make: "build-config"
            image: "namada-config"
          - make: "build-genesis"
            image: "namada-genesis"
          - make: "build-namada"
            image: "namada"
          - make: "build-namada-inst"
            image: "namada-inst"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.regsitry_url }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
      - name: Build & Push Image ${{ matrix.images.image }} with sha commit ${{ github.event.inputs.commit }}
        run: |
          registry_url="${{ env.regsitry_url }}" sha=${{ github.event.inputs.commit }} make ${{ matrix.images.make }}
          docker push ${{ env.regsitry_url }}/${{ matrix.images.image }}