name: Rebuild Namada images

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "The namada SHA commit to build"
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        images:
          - make: "build-config"
            image: "config"
          - make: "build-genesis"
            image: "genesis"
          - make: "build-namada"
            image: "namada"
          - make: "build-namada-inst"
            image: "namada-inst"

    steps:
    - name: Build image ${{ matrix.images.name }}
      run: sha=${{ github.event.inputs.commit }} make ${{ matrix.images.make }}