name: Run antithesis (triggerable)

on:
  workflow_dispatch:
    inputs:
      namada_genesis_docker_tag:
        description: 'The docker tag of the namada genesis docker images'
        required: true
        type: string
      namada_docker_tag:
        description: 'The docker tag of the namada docker images'
        required: true
        type: string
      workload_tag:
        description: 'The docker tag of the workload docker images'
        required: true
        type: string
      duration:
        description: Duration of the experiment

jobs:
  antithesis:
    runs-on: [ubuntu-latest]
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.7
        with:
          config_image: namada-config:${{ github.event.inputs.namada_genesis_docker_tag }}
          notebook_name: namada2
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-genesis:${{ github.event.inputs.namada_genesis_docker_tag }},namada:${{ github.event.inputs.namada_docker_tag }},workload:${{ github.event.inputs.workload_tag }},check:latest,masp-indexer-block-filter:master,masp-indexer-webserver:master,masp-indexer-chain:master,indexer-chain:main,indexer-transactions:main
          email_recipients: |
            gianmarco@heliax.dev,yuji@heliax.dev,heliax-antithesis-aaaammxjv6zgaqxcdury4ktshq@antithesisgroup.slack.com
          additional_parameters: |
            custom.duration=${{ github.event.inputs.duration }}
            custom.faults=true