name: Run antithesis (triggerable)

on:
  workflow_dispatch:
    inputs:
      namada_docker_tag:
        description: 'The docker tag of the namada docker images'
        required: true
        type: string
      scenario_tester_docker_tag:
        description: 'The docker tag of the scenario tester image'
        required: true
        type: string
      duration:
        description: The duration of the experiment
      faults:
        description: If faults needs to be introduced

jobs:
  antithesis:
    runs-on: [ubuntu-latest]
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.5
        with:
          config_image: namada-config:${{ github.event.inputs.namada_docker_tag }}
          notebook_name: namada2
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-genesis:${{ github.event.inputs.namada_docker_tag }},namada:${{ github.event.inputs.namada_docker_tag }},namada-scenario-tester:${{ github.event.inputs.scenario_tester_docker_tag }},check:latest
          email_recipients: |
            gianmarco@heliax.dev,heliax-antithesis-aaaammxjv6zgaqxcdury4ktshq@antithesisgroup.slack.com
          additional_parameters: |
            custom.duration=${{ github.event.inputs.duration }}
            custom.faults=${{ github.event.inputs.faults }}