name: Run antithesis (triggerable)

on:
  workflow_dispatch:
    inputs:
      namada_docker_tag:
        description: 'The docker tag of the namada docker images'
        required: true
        type: string
      scenario_tester_docker_tag:
        description: 'The docker tag of the scenario tester image'
        required: true
        type: string
      timeouts:
        type: choice
        description: Timeout definition
        options:
        - short
        - medium
        - long
      faults:
        type: choice
        description: Faults definition
        options:
        - baseline
        - minimal
      run_type:
        type: choice
        description: RunType definition
        options:
        - default_antithesis
        - determinator__2000_200
        - default_fuzzer

jobs:
  antithesis:
    runs-on: [ubuntu-latest]
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.5
        with:
          notebook_name: namada
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-config:${{ github.event.inputs.namada_docker_tag }},namada-genesis:${{ github.event.inputs.namada_docker_tag }},namada:${{ github.event.inputs.namada_docker_tag }},namada-scenario-tester:${{ github.event.inputs.scenario_tester_docker_tag }}
          additional_parameters: |-
            custom.timeouts=${{ github.event.inputs.timeouts }}
            custom.faults=${{ github.event.inputs.faults }}
            custom.run_type=${{ github.event.inputs.run_type }}
            custom.testing_config=namada-default