name: Run workload test

on:
  pull_request:
    paths:
      - 'workload/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test-workload:
      name: Run workload test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
            username: _json_key
            password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
        - name: Login to ghcr.io
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Cache Docker layers
          uses: actions/cache@v4
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-docker-compose-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-docker-compose-
        - name: Docker compose build
          run:  docker compose -f config/docker-compose-ci.yml build
        - name: Run test
          run: ./ci.sh
