name: Validate docker compose

on:
  workflow_dispatch:
    inputs:
        namada_tag:
          description: "The namada images tag"
          required: true
          type: string
        workload_tag:
          description: "The workload tag"
          required: true
          type: string
        check_tag:
          description: "The check tag"
          required: true
          type: string
        masp_tag:
          description: "The masp indexer tag"
          required: true
          type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      antithesis_registry_url: us-central1-docker.pkg.dev/molten-verve-216720/heliax-repository
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run validate script
        run: |
          pip3 install pyyaml
          python3 .github/workflows/scripts/validate.py
        env:
          NAMADA_TAG: ${{ github.event.inputs.namada_tag }}
          CHECK_TAG: ${{ github.event.inputs.check_tag }}
          WORKLOAD_TAG: ${{ github.event.inputs.workload_tag }}
          MASP_TAG: ${{ github.event.inputs.masp_tag }}
          