name: Run antithesis on weekly

on:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  weekly:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
      matrix:
        runs:
          - image: "main"
            timeout: "long"
            faults: "baseline"
            run_type: "default_antithesis"
            
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.5
        with:
          notebook_name: ${{ github.event.inputs.workload_type }}
          tenant: heliax
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          images: namada-config:${{ matrix.runs.image }},namada-genesis:${{ matrix.runs.image }},namada:${{ matrix.runs.image }},namada-scenario-tester:latest
          additional_parameters: |-
            custom.timeouts=${{ matrix.runs.timeout }}
            custom.faults=${{ matrix.runs.faults }}
            custom.run_type=${{ matrix.runs.run_type }}
            custom.testing_config=namada-default